export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const SINGLE_CATEGORY_REQUEST = 'SINGLE_CATEGORY_REQUEST';
export const SINGLE_CATEGORY_SUCCESS = 'SINGLE_CATEGORY_SUCCESS';
export const SINGLE_CATEGORY_FAIL = 'SINGLE_CATEGORY_FAIL';

export const NEW_CATEGORY_REQUEST = 'NEW_CATEGORY_REQUEST';
export const NEW_CATEGORY_SUCCESS = 'NEW_CATEGORY_SUCCESS';
export const NEW_CATEGORY_FAIL = 'NEW_CATEGORY_FAIL';
export const NEW_CATEGORY_RESET = 'NEW_CATEGORY_RESET'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET'