export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL';

export const TASK_CATEGORY_REQUEST = 'TASK_CATEGORY_REQUEST';
export const TASK_CATEGORY_SUCCESS = 'TASK_CATEGORY_SUCCESS';
export const TASK_CATEGORY_FAIL = 'TASK_CATEGORY_FAIL';

export const NEW_TASK_REQUEST = 'NEW_TASK_REQUEST';
export const NEW_TASK_SUCCESS = 'NEW_TASK_SUCCESS';
export const NEW_TASK_FAIL = 'NEW_TASK_FAIL';
export const NEW_TASK_RESET = 'NEW_TASK_RESET';

export const GET_TASK_REQUEST = 'GET_TASK_REQUEST';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAIL = 'GET_TASK_FAIL';

export const COMPLETE_TASK_REQUEST = 'COMPLETE_TASK_REQUEST';
export const COMPLETE_TASK_SUCCESS = 'COMPLETE_TASK_SUCCESS';
export const COMPLETE_TASK_FAIL = 'COMPLETE_TASK_FAIL';
export const COMPLETE_TASK_RESET = 'COMPLETE_TASK_RESET';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL';
export const DELETE_TASK_RESET = 'DELETE_TASK_RESET';

export const COMMENT_TASK_REQUEST = 'COMMENT_TASK_REQUEST';
export const COMMENT_TASK_SUCCESS = 'COMMENT_TASK_SUCCESS';
export const COMMENT_TASK_FAIL = 'COMMENT_TASK_FAIL';
export const COMMENT_TASK_RESET = 'COMMENT_TASK_RESET'
